/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE WITHOUT COPYING TO YOUR SRC DIRECTORY.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues,
 * or contact author landerlyoung@gmail.com.
 */

/* C++ header file for class rainmtime.com.demorepo.ndk.JennyTest */
#pragma once

#include <jni.h>

namespace  JennyTest {

//DO NOT modify
static constexpr auto FULL_CLASS_NAME = "rainmtime/com/demorepo/ndk/JennyTest";



/*
 * Class:     rainmtime_com_demorepo_ndk_JennyTest
 * Method:    public int add(int a, int b)
 * Signature: (II)I
 */
jint add(JNIEnv *env, jobject thiz, jint a, jint b);


/*
 * Class:     rainmtime_com_demorepo_ndk_JennyTest
 * Method:    public void cpp_magic(java.lang.String s, byte[] data)
 * Signature: (Ljava/lang/String;[B)V
 */
void cpp_magic(JNIEnv *env, jobject thiz, jstring s, jbyteArray data);


/*
 * Class:     rainmtime_com_demorepo_ndk_JennyTest
 * Method:    public void sub(int a, int b)
 * Signature: (II)V
 */
void sub(JNIEnv *env, jobject thiz, jint a, jint b);




/**
 * register Native functions
 * @returns success or not
 */
bool registerNativeFunctions(JNIEnv *env);

} //endof namespace JennyTest
